#Restrictions
#  Each section has a true/false "enabled" and a value
#   Values vary by setting:
#     Reputation: A number, can have decimal eg 0.1
#     Bans: An integer. 
#     Flags: Array of flags not allowed to join the server
#       example: value: ['SCA'] or ['SCA','ASB']
#   The value for reputation can have a decimal eg. 0.1
#   
#  Users attempting to join counts AT or above/below that value are blocked
#   Example:
#    Setting reputation to 0 means users with 0 rep or lower cannot join
#     Bans to 5 means users with 5 bans or more cannot join
#
#  Settings:
#   timeout: How long a user's data is cached, in minutes
#             minimum 5
#   logblock: Enable LogBlock intergration to automatically rollback
#             players when banned
#             default: false
#   defaultreason: The default ban reason used if none is provided
#             default: 'You have been banned!'
#   useriprecording: Submit username and IP address to MCBlockIt when a
#                    user logs in. Used for alt account tracking.
#             default: true
#   loginnotification: Notify admins (with associated permissions) upon
#                      user login about their account status
#             default: true
APIKEY: changeme
restrictions:
  reputation:
    enable: true
    value: 0
  bans:
    enable: false
    value: 5
  flags:
    enable: false
    value: ['SCA']
settings:
  timeout: 5
  logblock: false
  defaultreason: You have been banned!
  useriprecording: true
  loginnotification: true