name: MCBlockIt
main: it.mcblock.mcblockit.bukkit.MCBlockItPlugin
description: ${project.description}
author: mbaxter
url: http://mcblock.it
version: '${project.version}'
commands:
  ban:
    usage: /ban username reason
    aliases: [b]
    description: Ban a user
    permission: mcblockit.ban.local
    permission-message: You may not local ban.
  gban:
    usage: /gban username reason
    aliases: [gb]
    description: Global ban a user
    permission: mcblockit.ban.global
    permission-message: You may not global ban.
  kick:
    usage: /kick username [reason]
    aliases: [k]
    description: Kick a user
    permission: mcblockit.kick
    permission-message: You may not kick.
  unban:
    usage: /unban username
    description: Unban a user
    aliases: [pardon]
    permission: mcblockit.unban
    permission-message: You may not unban.
  lookup:
    usage: /lookup username
    description: View user record
    permission: mcblockit.lookup
    permission-message: You may not lookup.
permissions:
  mcblockit.ban.local:
    description: Able to local ban a user
  mcblockit.ban.global:
    description: Able to global ban a user
  mcblockit.ban:
    description: Able to ban a user globally and locally
    children:
      mcblockit.ban.local: true
      mcblockit.ban.global: true
  mcblockit.kick:
    description: Able to kick a user
  mcblockit.notifications:
    description: Receive system notices
  mcblockit.unban:
    description: Able to unban a user
  mcblockit.lookup:
    description: Able to lookup user history
  mcblockit.*:
    description: Grant ALL the nodes
    default: op
    children:
      mcblockit.ban: true
      mcblockit.kick: true
      mcblockit.notifications: true
      mcblockit.unban: true
      mcblockit.lookup: true